require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GameRoomsController do

  # This should return the minimal set of attributes required to create a valid
  # GameRoom. As you add validations to GameRoom, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GameRoomsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all game_rooms as @game_rooms" do
      game_room = GameRoom.create! valid_attributes
      get :index, {}, valid_session
      assigns(:game_rooms).should eq([game_room])
    end
  end

  describe "GET show" do
    it "assigns the requested game_room as @game_room" do
      game_room = GameRoom.create! valid_attributes
      get :show, {:id => game_room.to_param}, valid_session
      assigns(:game_room).should eq(game_room)
    end
  end

  describe "GET new" do
    it "assigns a new game_room as @game_room" do
      get :new, {}, valid_session
      assigns(:game_room).should be_a_new(GameRoom)
    end
  end

  describe "GET edit" do
    it "assigns the requested game_room as @game_room" do
      game_room = GameRoom.create! valid_attributes
      get :edit, {:id => game_room.to_param}, valid_session
      assigns(:game_room).should eq(game_room)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GameRoom" do
        expect {
          post :create, {:game_room => valid_attributes}, valid_session
        }.to change(GameRoom, :count).by(1)
      end

      it "assigns a newly created game_room as @game_room" do
        post :create, {:game_room => valid_attributes}, valid_session
        assigns(:game_room).should be_a(GameRoom)
        assigns(:game_room).should be_persisted
      end

      it "redirects to the created game_room" do
        post :create, {:game_room => valid_attributes}, valid_session
        response.should redirect_to(GameRoom.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved game_room as @game_room" do
        # Trigger the behavior that occurs when invalid params are submitted
        GameRoom.any_instance.stub(:save).and_return(false)
        post :create, {:game_room => { "name" => "invalid value" }}, valid_session
        assigns(:game_room).should be_a_new(GameRoom)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GameRoom.any_instance.stub(:save).and_return(false)
        post :create, {:game_room => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested game_room" do
        game_room = GameRoom.create! valid_attributes
        # Assuming there are no other game_rooms in the database, this
        # specifies that the GameRoom created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GameRoom.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => game_room.to_param, :game_room => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested game_room as @game_room" do
        game_room = GameRoom.create! valid_attributes
        put :update, {:id => game_room.to_param, :game_room => valid_attributes}, valid_session
        assigns(:game_room).should eq(game_room)
      end

      it "redirects to the game_room" do
        game_room = GameRoom.create! valid_attributes
        put :update, {:id => game_room.to_param, :game_room => valid_attributes}, valid_session
        response.should redirect_to(game_room)
      end
    end

    describe "with invalid params" do
      it "assigns the game_room as @game_room" do
        game_room = GameRoom.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GameRoom.any_instance.stub(:save).and_return(false)
        put :update, {:id => game_room.to_param, :game_room => { "name" => "invalid value" }}, valid_session
        assigns(:game_room).should eq(game_room)
      end

      it "re-renders the 'edit' template" do
        game_room = GameRoom.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GameRoom.any_instance.stub(:save).and_return(false)
        put :update, {:id => game_room.to_param, :game_room => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested game_room" do
      game_room = GameRoom.create! valid_attributes
      expect {
        delete :destroy, {:id => game_room.to_param}, valid_session
      }.to change(GameRoom, :count).by(-1)
    end

    it "redirects to the game_rooms list" do
      game_room = GameRoom.create! valid_attributes
      delete :destroy, {:id => game_room.to_param}, valid_session
      response.should redirect_to(game_rooms_url)
    end
  end

end
